### ISSUE TITLE
Show Iridium News Panel not showing anything

### ISSUE THREAD

**Issue by h0h0h0** [iridiumdev/iridium-wallet#11]
I turned on Show Iridium News flag and i see the panel on Overview screen but no news.  Do we need to repoint the RSS feed or do we post an Announcement or something? :)

MacOS Wallet. 4.0.1

**Comment by steevebrush** [comment]
Yes, as the main website is now https only, I have to change it in the url rss feed.
I already correct it but this need a new build release.
