### ISSUE TITLE
Mac 5.0.0 wallet - "Days ago" block counter during load does not update

### ISSUE THREAD

**Issue by h0h0h0** [iridiumdev/iridium-wallet#34]
**Describe the bug**
Opened new wallet first time. During syncronization note the date of last block as it loads. It used to be the the time since the block being loaded (4 days, three days). Now it's fixed to the date of the last block.

This is a minor bug since it does not affect the block synchronization.

**Comment by steevebrush** [comment]
This is expected : blockchain height is the current mined block #, and the date after is the last mined block timestamp. maybe I have to change the '@' to 'last mined block' ?
