### ISSUE TITLE
Wallet Disconnected - Stuck

### ISSUE THREAD

**Issue by MiamiJack** [iridiumdev/iridium-wallet#35]
Using the latest IRD wallet 2.1.3 / QT on 5.10.0
When opening the wallet it shows synchronization but shows 1136 Days 12 hours ago.
I erased the DB, but no matter what this is my error, and the bottom right shows disconnected.

Any suggestions?
Thanks

**Comment by steevebrush** [comment]
The latest version will alway be here : https://github.com/iridiumdev/iridium-wallet/releases/latest
About your problem, we are now at the version 5.0.0. It's normal that this old version doesn't sync as there has been 3 hard forks on the blockchain during this time. Use the "real" latest version :-)
