### ISSUE TITLE
Do not put an AppImage into another archive

### ISSUE THREAD

**Issue by probonopd** [iridiumdev/iridium-wallet#5]
Please DO NOT put an AppImage into another archive like a `.tar.bz2`. 

While it may be tempting to avoid users having to set permission, this breaks desktop integration with the optional `appimaged` daemon, among other things. Besides, the beauty of the AppImage format is that you never need to unpack anything. Furthermore, packing an AppImage into some form of archive prevents the AppImage from being added to the central catalog of available AppImages at https://github.com/AppImage/AppImageHub.

https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#common-mistake

**Comment by steevebrush** [comment]
ok ok ok, I never will do this again...
